// An original question / answer composition. All pitched voices share the same harmony.
export type SectionId = "intro" | "dialogue" | "rise" | "return";
export const sections = [
  {
    id: "intro",
    name: "Вступление",
    description: "Электропиано и звон; затем входят pad, бас и первые удары",
  },
  {
    id: "dialogue",
    name: "Диалог",
    description:
      "Вступают второй синт и стекло, инструменты обмениваются фразами",
  },
  {
    id: "rise",
    name: "Подъём",
    description: "Полный состав, тяжёлый бит и короткие паузы перед ответами",
  },
  {
    id: "return",
    name: "Возвращение",
    description: "Аккомпанемент редеет, мелодия возвращается к начальной теме",
  },
] as const;
export const chords = {
  dm: {
    name: "Dm",
    bass: 26,
    body: [50, 57, 53],
    ghost: [69, 72, 65],
    chime: [74, 77, 81],
    glass: 86,
  },
  bb: {
    name: "B♭",
    bass: 34,
    body: [46, 53, 50],
    ghost: [65, 62, 70],
    chime: [70, 74, 77],
    glass: 89,
  },
  am: {
    name: "Am",
    bass: 33,
    body: [45, 52, 48],
    ghost: [64, 60, 69],
    chime: [72, 76, 81],
    glass: 88,
  },
  f: {
    name: "F",
    bass: 29,
    body: [53, 48, 57],
    ghost: [69, 72, 65],
    chime: [72, 77, 81],
    glass: 84,
  },
  c: {
    name: "C",
    bass: 36,
    body: [48, 55, 52],
    ghost: [67, 64, 72],
    chime: [72, 76, 79],
    glass: 88,
  },
};
export type ChordId = keyof typeof chords;
export const harmony: ChordId[] = [
  "dm",
  "f",
  "bb",
  "am",
  "dm",
  "f",
  "bb",
  "c",
  "f",
  "bb",
  "c",
  "am",
  "dm",
  "bb",
  "am",
  "dm",
];
export function arrangementAt(step: number) {
  const bar = Math.floor(step / 16) % 16,
    section = sections[Math.floor(bar / 4)],
    chord = chords[harmony[bar]];
  return {
    bar,
    section: { ...section, description: barDescriptions[bar] },
    chord,
  };
}

// Instrument entrances and dropouts across the sixteen bars.
export const layerPlan = [
  ["piano", "chime"],
  ["piano", "chime", "pad"],
  ["piano", "chime", "pad", "bass"],
  ["piano", "chime", "bass", "body", "beat"],
  ["piano", "chime", "bass", "body", "beat", "ghost", "tower"],
  ["piano", "chime", "bass", "body", "beat", "bow", "glass"],
  ["piano", "chime", "bass", "beat", "ghost", "pad", "pluck", "machine"],
  ["piano", "chime", "bass", "body", "beat", "bow", "noise"],
  [
    "piano",
    "chime",
    "bass",
    "body",
    "beat",
    "ghost",
    "pad",
    "bow",
    "tower",
    "machine",
  ],
  [
    "piano",
    "chime",
    "bass",
    "body",
    "beat",
    "glass",
    "pluck",
    "tower",
    "noise",
  ],
  [
    "piano",
    "chime",
    "bass",
    "beat",
    "ghost",
    "pad",
    "glass",
    "pluck",
    "machine",
  ],
  [
    "piano",
    "chime",
    "bass",
    "body",
    "beat",
    "ghost",
    "bow",
    "tower",
    "noise",
    "machine",
  ],
  ["piano", "chime", "pad", "bow", "tower"],
  ["piano", "chime", "bass", "ghost", "pluck"],
  ["piano", "chime", "bow"],
  ["piano", "chime", "noise"],
] as const;
export const barDescriptions = [
  "Только электропиано и лёгкий звон",
  "Под темой появляется тёплый pad",
  "Входит глубокий бас",
  "Подключаются BODY, бочка и хай-хэты",
  "Полный бит, второй синт и удар набата",
  "Второй синт уступает место смычковому стеклу",
  "Возвращается второй синт; pluck и щелчки отвечают теме",
  "Во второй половине такта ритм замолкает — остаётся протяжный ответ",
  "Кульминация: полный ритм, оба синта и набат",
  "Стеклянные акценты сменяют протяжный голос",
  "BODY делает паузу; второй синт и pluck продолжают движение",
  "Короткая ритмическая пауза перед тихим возвращением",
  "Бит уходит; остаются тема, pad и низкий колокол",
  "Последний ответ баса и второго синта",
  "Тема и протяжное стекло без ритма",
  "Только тема, звон и тихий воздух перед повтором",
];
